spring:
  application:
    name: simple-java
  temporal:
    namespace: default
    connection:
      target: 127.0.0.1:7233
    workers:
      - name: simple-worker
        task-queue: simple-task-queue
    workersAutoDiscovery:
      packages:
      - com.example.workflows
      - com.example.activities

echo:
  number: 4
